# Purpose of this file:
# Store constants used throughout project.

ALPHA_CSV = 'alpha_country_codes.csv'
abv_set = {'APEC', 'ASEAN','CIDA', 'FAO', 'FTAA', 'G8', 'IMF', 'ICJ', 'IISD',
'ICC', 'IOC', 'NAFTA', 'NATO', 'NORAD', 'OAS', 'OECD', 'OHCHR', 'UNAIDS',
'UNDP', 'UNESCO', 'UNICEF', 'WHO', 'WTO', 'WWF', '2G', '3G', '4G', '5G',  'Brexit',
'6G', 'HIV', 'AAPC', 'ABMC', 'ACC', 'ACDA', 'ACF', 'ACHP', 'ACSES',
'ACSL', 'ACYF', 'ADA', 'ADB', 'ADC', 'ADD', 'AFDB', 'AFDC', 'AFIS',
'AFRC', 'AFRL', 'AFROTC', 'AFRTS', 'AFS', 'AFSC', 'AFSPC', 'AGO',
'AGRICOLA', 'AHCPR', 'AHPCRC', 'AHRQ', 'AHS', 'AID', 'AIDS', 'AIRS', 'AME',
'AMES', 'AMS', 'Amtrak', 'ANA', 'ANG', 'ANL', 'AOA', 'APA',
'APHIS', 'API', 'AR', 'ARB', 'ARBA', 'ARC', 'ARL', 'ARNet', 'APRA',
'ARS', 'ATF', 'ATSDR', 'BARC', 'BEA', 'BEIS', 'BEP', 'BBER', 'BEST',
'BFRL', 'BHPr', 'BIA', 'BIC', 'BIMAS', 'BIS', 'BJA', 'BJS', 'BLM',
'BLS', 'BMDO', 'BNA', 'BOP', 'BOR', 'BPA', 'BPD', 'BPHC', 'BRB',
'BRD', 'BRFSS', 'BSC', 'BTS', 'BUD', 'BVA', 'CAGE', 'CAME', 'CBD',
'CBER', 'CBIAC', 'CBO', 'CCB', 'CCC', 'CCP', 'CCR', 'CCP', 'CDBG', 'CDC', 'CDEL',
'CDER', 'CDFI', 'CDRH', 'CEA', 'CEDR', 'CEN', 'CEOS', 'CEPPO', 'CEPS',
'CEQ', 'CERCLIS', 'CETEC', 'CFDA', 'CFOC', 'CFR', 'CFSAN', 'CFTC',
'CHAMPVA', 'CHID', 'CIA', 'CIAO', 'CIC', 'CID', 'CIPRIS', 'CIT',
'CITES', 'CMHS', 'CMS', 'CMV', 'CNPP', 'CNS', 'CO', 'Conrail', 'CONSER',
'COP', 'COPS', 'CPI', 'CPMS', 'CPO', 'CPSC', 'CRC', 'CRISP', 'CRP',
'CRS', 'CSAP', 'CSAT', 'CSB', 'CSE', 'CSI', 'CSPS', 'CSR', 'CSREES',
'CTEP', 'CUAP', 'CWC', 'CxD', 'DA', 'DARPA', 'DAU', 'DCAA', 'DCLG',
'DCMS', 'DCSF', 'DDC', 'DE&S', 'DEA', 'DeCA', 'DECC', 'Defra', 'DEL',
'DESA', 'DESC', 'DETR', 'DFAS', 'DfE', 'DfEE', 'DfES', 'DfID', 'DfT',
'DH', 'DIA', 'DINFOS', 'DISA', 'DIT', 'DIUS', 'DLA', 'DLAPS', 'DLIS',
'DLSA', 'DMDC', 'DMO', 'DNFSB', 'DNSC', 'DOC', 'DOD', 'DODEA', 'DoDISS',
'DoDSSP', 'DOE', 'DOI', 'DOJ', 'DOL', 'DORRA', 'DOS', 'DOT', 'DPC',
'DPCP', 'DPL', 'DPM', 'DPMO', 'DRMS', 'DSCA', 'DSS', 'DTIC', 'DTLR',
'DTRA', 'DVLA', 'DWP', 'EAR', 'ECA', 'ECI', 'ECIE', 'ECOSOC', 'ECP',
'ED', 'EDA', 'EDGAR', 'EEOC', 'EHP', 'EIA', 'EIS', 'EM', 'EML', 'ENC',
'EO', 'EOAF', 'EOIR', 'EOUSA', 'EOWS', 'EPA', 'EREN', 'ERG', 'ERIC',
'ERL', 'EROD', 'ERS', 'ESA', 'ESDIM', 'ETA', 'Ex-Im Bank', 'FAA',
'Fannie Mae', 'FAO', 'FAR', 'Farmer Mac', 'FAS', 'FASAB', 'FBI',
'FBIS', 'FCA', 'FCC', 'FDA', 'FDIC', 'FEC', 'FEDRIP', 'FEMA', 'FERC',
'Fermilab', 'FFB', 'FHA', 'FHFB', 'FHWA', 'FIA', 'FINCEN', 'FIPS',
'FLC', 'FLETC', 'FLRA', 'FMC', 'FMCS', 'FMCSA', 'FMLA', 'FMS', 'FMSHRC',
'FNCS', 'FNMA', 'FNS', 'FoI', 'FOIA', 'FOMC', 'FPDC', 'FR', 'FRA',
'FRB', 'FRS', 'FRTIB', 'FS', 'FSA', 'FSIS', 'FSS', 'FTA', 'FTC',
'FTE', 'FTS', 'FWS', 'FYSB', 'G6', 'G7', 'GAD', 'GAO', 'GATT', 'GCMD',
'GILS', 'Ginnie Mae', 'GIPSA', 'GIS', 'GNIS', 'GNMA', 'GOP', 'GPO',
'GPRA', 'GPS', 'GSA', 'GSFC', 'GWA', 'GWoB', 'HAB', 'HAC', 'HCS', 'Her',
'HHS', 'HIRS', 'HMRC', 'HO', 'HPCC', 'HRSA', 'HSB', 'HUD', 'IA', 'IACB',
'IADRWG', 'IAEA', 'IAEGC', 'IAF', 'IBB', 'ICAF', 'ICAO', 'ICC', 'IfG',
'IFRS', 'IHS', 'IIP', 'ILAB', 'ILO', 'IMLS', 'INEEL', 'INF', 'INL',
'INS', 'INSS', 'INTERPOL', 'IO', 'IOM', 'IPA', 'IRMC', 'IRS', 'IT',
'ITA', 'ITC', 'JAG', 'JCS', 'JEC', 'JFSC', 'JPL', 'JSC', 'KAPL', 'KSC',
'LANL', 'Law', 'LBL', 'LLNL', 'LOC', 'LOCIS', 'LSC', 'MAC', 'MARAD',
'MARVEL', 'MBDA', 'MCHB', 'MCTL', 'MedPAC', 'MeSH', 'MIGA', 'MMS',
'MMWR', 'MoD', 'MoG', 'MoJ', 'MPA', 'MSA', 'MSEL', 'MSHA', 'MSPB',
'NACIC', 'NAFTA', 'NAL', 'NAO', 'NARA', 'NARFE', 'NASA', 'NASM',
'NASS', 'NBII', 'NBL', 'NCC', 'NCCAM', 'NCCDPHP', 'NCCIC', 'NCD',
'NCDC', 'NCEH', 'NCES', 'NCHS', 'NCHSTP', 'NCI', 'NCID', 'NCIPC',
'NCIS', 'NCJRS', 'NCLIS', 'NCPC', 'NCRR', 'NCS', 'NCTR', 'NCUA',
'NCVHS', 'NDIC', 'NDU', 'NEA', 'NEC', 'NEGP', 'NEH', 'NEI', 'NEIC',
'NERSC', 'NESDIS', 'NETL', 'NFA', 'NGA', 'NGDC', 'NGO', 'NGS', 'NHI',
'NHIC', 'NHLBI', 'NHPRC', 'NHS', 'NHTSA', 'NIA', 'NIAAA', 'NIAID',
'NIAMS', 'NIC', 'NICHD', 'NICS', 'NIDCD', 'NIDCR', 'NIDDK', 'NIDRR',
'NIEHS', 'NIFC', 'NIFL', 'NIGC', 'NIGMS', 'NIH', 'NIJ', 'NIMA', 'NIMH',
'NINDS', 'NINR', 'NIO', 'NIOSH', 'NIPA', 'NIST', 'NISTIR', 'NLE',
'NLRB', 'NMB', 'NMFS', 'NNSA', 'NOAA', 'NODC', 'NOS', 'NPCR', 'NPOESS',
'NPS', 'NPTO', 'NR', 'NRC', 'NRCS', 'NRDP', 'NREN', 'NREVSS', 'NRL',
'NRO', 'NRPC', 'NS&I', 'NSA', 'NSC', 'NSF', 'NSTL', 'NTIA', 'NTIS',
'NTP', 'NTSB', 'NVSS', 'NWC', 'NWCG', 'NWS', 'NWTRB', 'OA', 'OAC',
'OACU', 'OAIT', 'OALJ', 'OAR', 'OAS', 'OASDI', 'OAT', 'OBI', 'OBL',
'OBR', 'OCC', 'OCD', 'OCE', 'OCR', 'OCRWM', 'OCS', 'OCSE', 'ODEP',
'ODP', 'ODPM', 'OECA', 'OECD', 'OEGT', 'OELA', 'OERI', 'OES', 'OESE',
'OFA', 'OFAC', 'OFCCP', 'OFHEO', 'OFM', 'OFR', 'OGE', 'OGP', 'OGWDW',
'OHASIS', 'OHRP', 'OIG', 'OIIA', 'OJJDP', 'OJP', 'OLAW', 'OLMS', 'OMAO',
'OLMS', 'OMAO', 'OMAR', 'OMH', 'OMHAR', 'OMM', 'ONDCP', 'ONR', 'ONS',
'OPA', 'OPE', 'OPEC', 'OPHS', 'OPIC', 'OPM', 'OPPTS', 'ORA', 'ORACBA',
'ORD', 'ORHP', 'ORI', 'ORMH', 'ORNL', 'ORR', 'ORWH', 'OSAC', 'OSBP',
'OSC', 'OSCAR', 'OSCE', 'OSDBU', 'OSERS', 'OSF', 'OSHA', 'OSHRC', 'OSM',
'OST', 'OSTI', 'OSTP', 'OSWER', 'OTA', 'OTJ', 'OTS', 'OTT', 'OVAE',
'OVC', 'OWBO', 'OWCP', 'OWH', 'PAC', 'PAHO', 'PAM', 'PASC', 'PBGC',
'PBS', 'PC', 'PCBE', 'PCC', 'PCIE', 'PESA', 'PFIAB', 'PHA', 'PHN',
'PHPPO', 'PHPS', 'PHS', 'PHTN', 'PIH', 'PLLI', 'PM', 'PNNL', 'POTUS',
'POTUK','POW', 'MP', 'PPQ', 'PRC', 'PRM', 'PSC', 'PSE', 'PTO', 'PUMS',
'PWBA', 'QDS', 'RA', 'RAG', 'RAME', 'RBS', 'RD',
'RDEL', 'REE', 'REIS', 'RHS', 'RICHS', 'RMA', 'ROTC', 'RRB', 'RSA',
'RSPA', 'RUS', 'SAMHSA', 'SAVE', 'SBA', 'Scot', 'SCS', 'SDFS', 'SDWIS',
'SEC', 'SEDAC', 'SEER', 'SEO', 'HEO', 'SERC', 'SG', 'SGLI', 'SI', 'SIC',
'SIES', 'SITES', 'SJI', 'SLAC', 'SLSDC', 'SNL', 'SR', 'SRP', 'SRS',
'SS', 'SSA', 'SSI', 'SSS', 'START', 'Stat.', 'STB', 'STI', 'TA', 'TAA',
'TANF', 'TASC', 'TDA', 'TFF', 'TIC', 'TIPS', 'TME', 'TSA', 'TSI', 'TSO',
'TSP', 'TVA', 'UKREP', 'VA', 'VBA', 'VETS', 'VGLI', 'VHA', 'VISTA',
'VOA', 'Wal', 'WAPA', 'WB', 'WG', 'WGA', 'WHWO', 'WHO', 'WIC', 'WMI',
'WNET', 'WSMR', 'ZIP', 'AAA', 'bde', 'bn', 'CINC', 'CIS', 'CO',
'DARPA', 'ed edit', 'MD', 'MoD', 'MRD', 'recce', 'RF', 'rgt', 'R&R',
'MSU', 'Gen Army', 'Col-Gen', 'Lt-Gen', 'Maj-Gen', 'Col', 'Lt-Col', 'Maj',
'Capt', 'Sr Lt', 'Lt', 'Jr Lt', 'WO', 'Adm Flt', 'Adm', 'V-Adm',
'R-Adm', 'CAPT-Lt', 'ABC', 'ACC', 'ACSC', 'ADB', 'APG', 'BAP',
'BFMFPS', 'BOF', 'CAFS', 'CAS', 'CNFC', 'CNFTEC', 'CSF', 'CARS',
'DAP', 'DFC', 'FAO', 'FCOU', 'GBAP', 'GDP', 'MAAF', 'MAF',
'MAP', 'MOA', 'MOC', 'MOFI', 'MWR', 'NEPA', 'NGOs', 'NGO', 'NFTES',
'NPC', 'SFU', 'SOA', 'UNDP', 'WFP', 'XFC', 'KFC', 'Yuan', 'ZFC', 'S&P', 'VIX',
'Dow Jones', 'Nasdaq', 'Russell', 'Hang Seng', 'Nikkei', 'TSX', 'KOSPI',
'NYSE', 'Euro Stoxx', 'Euronext', 'CBOT',
'CBOE', 'COMP', 'CME', 'ISM', 'PMI', 'RSI', 'G20', 'EU'}

class_markers = ['main', 'article', 'articles', 'title', 'headline', 'heading', 'headlines', 'headings']
ignore_articles = ('The View', 'Editorial', 'Lifestyle')

time_fillers = {'ago', 'second', 'seconds', 'minute', 'minutes', 'hour', 'hours', 'day', 'days', 'week', 'weeks',
                'month', 'months'}
blacklist = set(line.strip() for line in open('english_stop_words')).union(time_fillers)
english_words_set = set(line.strip() for line in open('words_alpha.txt'))
news_sites_to_names = {'https://www.nbcnews.com/': 'NBC',
                       'https://www.rt.com/': 'RT',
                       'https://www.scmp.com/': 'SCMP',
                       'https://www.bbc.com/news': 'BBC'}
list_of_links = list(news_sites_to_names.keys())
tags_to_scrape=['h1', 'h2', 'h3', 'h4', 'div', 'a']


news_options = [{'label': 'BBC', 'value': 'BBC'}, 
{'label': 'NBC News', 'value': 'NBC'},
{'label': 'South China Morning Post', 'value': 'SCMP'},
{'label': 'Russia Today', 'value': 'RT'}, 
{'label': '4 sources combined', 'value': ''}]